# Generated by Django 4.2.5 on 2023-10-05 00:03

import django.core.validators
from django.db import migrations, models
import test.helpers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhonebookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('primary_number', models.CharField(max_length=20, unique=True)),
                ('secondary_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.AlterField(
            model_name='file',
            name='file_upload',
            field=models.FileField(upload_to='files/', validators=[test.helpers.validators.FileValidator(content_types=('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',)), django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx'])]),
        ),
    ]
