# Generated by Django 4.2.5 on 2023-10-05 00:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_phonebookentry_remove_file_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebookentry',
            name='date_add',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='phonebookentry',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test.file'),
        ),
    ]
